//@version=4
strategy("教學範例-回測", overlay=true)  // 把 study 改成 strategy

sma20 = sma(close, 20)
sma60 = sma(close, 60)

plot(sma20, title="月線", color=color.green)
plot(sma60, title="季線", color=color.blue)

to_long = crossover(sma20, sma60)   // 黃金交叉
to_close = crossunder(sma20, sma60) // 死亡交叉

//plotchar(to_long, char="B", text="買", color=color.red, location=location.belowbar)
//plotchar(to_close, char="S", text="賣", color=color.green, location=location.abovebar)

strategy.entry("golden", strategy.long, qty=1000, when=to_long)
strategy.close("golden", qty=1000, when=to_close)
