//@version=4
study("昨日高低點標示", overlay=true)

// 時間週期參數允許值為：
// 1S, 5S, 15S, 30S - 秒間隔(圖表時間週期應小於或等於請求的時間週期)
// 從1到1440分鐘
// 從1D到365D 幾天
// 從1W到52W  幾週
// 從1M到12M  幾個月


dayhigh = security(syminfo.tickerid, "D", high)
daylow  = security(syminfo.tickerid, "D", low)

// style_line 會把線連起來，但 style_circles 不會把線連起來
plot(dayhigh[1], color= color.red , style=plot.style_line)
plot(daylow[1], color = color.green , style=plot.style_line)



